service: series-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  deploymentMethod: direct
  region: eu-central-1
  logRetentionInDays: 1

functions:
  create:
    handler: src/create.handler
    events:
      - http:
          method: post
          path: series
    description: Creates a serie
    environment:
      table: !Ref seriesTable
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:PutItem
        Resource:
          - Fn::GetAtt: [seriesTable, Arn]
  list:
    handler: src/list.handler
    events:
      - http:
          method: get
          path: series/{network}
    description: Lists series for a network
    environment:
      table: !Ref seriesTable
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:Query
        Resource:
          - Fn::GetAtt: [seriesTable, Arn]
  update:
    handler: src/update.handler
    events:
      - http:
          method: put
          path: series/{network}/{title}
    description: Updates a serie
    environment:
      table: !Ref seriesTable
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:UpdateItem
        Resource:
          - Fn::GetAtt: [seriesTable, Arn]
  delete:
    handler: src/delete.handler
    events:
      - http:
          method: delete
          path: series/{network}/{title}
    description: Deletes a serie
    environment:
      table: !Ref seriesTable
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:DeleteItem
        Resource:
          - Fn::GetAtt: [seriesTable, Arn]

plugins:
  - serverless-esbuild
  - serverless-iam-roles-per-function

resources:
  Resources:
    seriesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: network
            AttributeType: S
          - AttributeName: title
            AttributeType: S
        KeySchema:
          - AttributeName: network
            KeyType: HASH
          - AttributeName: title
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
